### ISSUE TITLE
NameError on running dlcIndex.exe on Windows

### ISSUE THREAD

**Issue by megamanhxh** [GarnetSunset/psDLCIndex#3]
# Problem
Running psDLCIndex@1.0.0 on Windows shows this error after inserting DLC link & confirming the fpkg location

![image](https://user-images.githubusercontent.com/2630110/151139214-05a9c091-51e1-4ae4-a2cb-60933ed55bc3.png)

```
Traceback (most recent call last):
  File "dlcIndex.py", line 153, in <module>
NameError: name 'exit' is not defined
[13616] Failed to execute script 'dlcIndex' due to unhandled exception!
```

# Solution
Maybe the import part is missing for `exit`
```
from sys import exit
exit()
```

**Comment by GarnetSunset** [comment]
strange, I already have an import  for that and I'm not running into that issue on my end.... we're already importing sys at the top so it shouldn't be a problem. Interpreter error I'd say.

**Comment by GarnetSunset** [comment]
I was not able to reproduce this on my machine or subsequent VMs. Grab the latest version.
