### ISSUE TITLE
No DLC for this app, mate

### ISSUE THREAD

**Issue by shun9092** [GarnetSunset/psDLCIndex#7]
It worked before the update, but it doesn't work after the update.

'No DLC for this app, mate' This error appears.

Other games downloaded in the past also don't work.

**Comment by GarnetSunset** [comment]
Hey there, I THINK this might be due to the full redesign of the playstation web store that took place last month, and unfortunately due to work I don't know if I'm going to be able to fix this at the moment, I'll ask my friends for a workaround and try to fix it, thanks!

**Comment by GarnetSunset** [comment]
Are you on the latest version? The main contributor @krugdenis has been updating the hell out of it (thank you!) and it should be up to date.

**Comment by shun9092** [comment]
yes, lastest version.

but it doesn't work.

would you like check please?

**Comment by krugdenis** [comment]
Thx, fixed it. I've done checks with CUSAxxxx only before

**Comment by GarnetSunset** [comment]
@krugdenis thank you so much you're the best. :)

**Comment by shun9092** [comment]
Thank you very much !
It work great !
