### ISSUE TITLE
All DLCs will not be downloaded

### ISSUE THREAD

**Issue by shun9092** [GarnetSunset/psDLCIndex#8]
I downloaded DLC as a test.

There were more types of DLCs downloaded from the Internet, but fewer were received through this program.

Can you check it for me?

For example https://store.playstation.com/en-hk/product/HP0177-CUSA17544_00-ASIAFULLGAME0000

When I use the program, I can download 30 of them.

When I received it on the Internet, it was 45.

**Comment by krugdenis** [comment]
Fixed

**Comment by shun9092** [comment]
@krugdenis 
Thank you !
It work great !
