### ISSUE TITLE
'No DLC for this app, mate' again maybe theme problem

### ISSUE THREAD

**Issue by shun9092** [GarnetSunset/psDLCIndex#9]
There is a situation where the same download is not possible after the update.

The number of downloads works the same, but some games don't work.

Probably not downloaded if there is no content but only theme

I downloaded it including the theme before fixing it, but the number of contents was insufficient.

But now I can download all the content, but I can't download the theme.

Can I make both content and themes available for download?

**Comment by krugdenis** [comment]
You can't download themes, only DLCs now. Previously it was a bug with downloading themes too. Fake themes are useless btw
